version: '3.7'

services:

  app:
    image: invoiceninja/invoiceninja:latest
    env_file: env
    ports:
      - "127.0.0.1:9000:9000"
    restart: always
    volumes:
      - ./config/hosts:/etc/hosts:ro
      - ./docker/app/public:/var/www/app/public:rw,delegated
      - ./docker/app/storage:/var/www/app/storage:rw,delegated
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/php-cli.ini:/usr/local/etc/php/php-cli.ini

    depends_on:
      - db

  db:
#    For auto DB backups comment out image and use the build block below
    build:
      context: ./config/mysql
    ports:
      - "127.0.0.1:3305:3306"
    restart: always
    env_file: env
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw,delegated

      # remove comments for next 4 lines if you want auto sql backups
      - ./docker/mysql/bak:/backups:rw
      - ./config/mysql/backup-script:/etc/cron.daily/daily:ro
      - ./config/mysql/backup-script:/etc/cron.weekly/weekly:ro
      - ./config/mysql/backup-script:/etc/cron.monthly/monthly:ro
